// Codex486 — Maps bundled avatar icon ids to lucide-react glyphs.
// All glyphs ship with the app (lucide-react, ISC license); no remote assets.
import {
  Aperture,
  BookOpen,
  Brain,
  CalendarClock,
  Clock3,
  Compass,
  Crown,
  Flame,
  Gem,
  Globe2,
  HardHat,
  Hourglass,
  Landmark,
  Moon,
  Orbit,
  Rocket,
  ScrollText,
  Shield,
  Star,
  Sun,
  Swords,
  Telescope,
  Timer,
  Trophy,
  WandSparkles,
  Zap,
} from 'lucide-react';

export const AVATAR_ICON_GLYPHS = {
  shield: Shield,
  hourglass: Hourglass,
  lightning: Zap,
  crown: Crown,
  compass: Compass,
  star: Star,
  book: BookOpen,
  flame: Flame,
  moon: Moon,
  sun: Sun,
  planet: Globe2,
  helmet: HardHat,
  crystal: Gem,
  trophy: Trophy,
  portal: Aperture,
  rocket: Rocket,
  sword: Swords,
  clock: Clock3,
  timer: Timer,
  calendar: CalendarClock,
  wand: WandSparkles,
  scroll: ScrollText,
  orbit: Orbit,
  telescope: Telescope,
  brain: Brain,
  landmark: Landmark,
};

export function getAvatarIconGlyph(iconId) {
  return AVATAR_ICON_GLYPHS[String(iconId || '').trim()] || null;
}
