import React, { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { AlertTriangle, CheckCircle2, ChevronDown, ClipboardCheck, Clock, Play, RefreshCw, ShieldAlert, X, XCircle } from 'lucide-react';
import { base44 } from '@/api/base44Client';

import gameLayoutSource from './GameLayout.jsx?raw';
import questionCardSource from './QuestionCard.jsx?raw';
import gameOverSource from './GameOver.jsx?raw';
import gamePageSource from '../../pages/Game.jsx?raw';
import lobbyRoomSource from '../../pages/LobbyRoom.jsx?raw';

const ST = { PASS: 'PASS', FAIL: 'FAIL', WARNING: 'WARNING', SKIPPED: 'SKIPPED' };
const LOOK = {
  PASS: ['#4ade80', CheckCircle2],
  FAIL: ['#f87171', XCircle],
  WARNING: ['#facc15', AlertTriangle],
  SKIPPED: ['#a1a1aa', Clock],
};
const CATS = [
  ['smoke', 'Smoke', '#67e8f9'],
  ['chat_removed', 'Online Chat Removal', '#fb7185'],
  ['lobby', 'Online Lobby', '#60a5fa'],
  ['spectator', 'Spectator Mode', '#c084fc'],
  ['sync', 'Multiplayer Sync', '#38bdf8'],
  ['winner', 'Online GameOver', '#facc15'],
  ['ui', 'UI Cleanup', '#2dd4bf'],
  ['offline', 'Offline Solo', '#c084fc'],
  ['records', 'Records/Admin', '#f59e0b'],
  ['perf', 'Performance', '#fde68a'],
  ['edge', 'Skipped / Edge', '#fca5a5'],
].map(([id, label, color]) => ({ id, label, color }));

const SOURCES = { 'GameLayout.jsx': gameLayoutSource, 'Game.jsx': gamePageSource, 'LobbyRoom.jsx': lobbyRoomSource, 'QuestionCard.jsx': questionCardSource, 'GameOver.jsx': gameOverSource };
const doneAt = () => new Date().toLocaleTimeString('tr-TR', { hour: '2-digit', minute: '2-digit', second: '2-digit' });
const res = (status, message, extra = {}) => ({ status, message, ...extra });
const pass = (message, extra) => res(ST.PASS, message, extra);
const fail = (message, extra) => res(ST.FAIL, message, extra);
const warn = (message, extra) => res(ST.WARNING, message, extra);
const skipped = (message, extra) => res(ST.SKIPPED, message, extra);
const eq = (actual, expected, message, extra = {}) => actual === expected ? pass(message, { actual, expected, ...extra }) : fail(message, { actual, expected, ...extra });
const yes = (actual, message, extra = {}) => actual ? pass(message, { actual: Boolean(actual), expected: true, ...extra }) : fail(message, { actual: Boolean(actual), expected: true, ...extra });
const norm = value => String(value || '').trim().toLocaleLowerCase('tr-TR');
const normalizeCode = value => String(value || '').trim().toUpperCase().replace(/\s+/g, '').replace(/[^\w]/g, '');
const qs = async () => base44.entities.Question.list('-created_date', 500);
const qpool = (items, cat = 'karisik') => items.filter(q => (cat === 'muzik' ? q.type === 'muzik' : q.type === 'metin')).filter(q => q.year >= 1900 && q.year <= 2026).filter(q => cat === 'karisik' || q.category === cat).filter(q => q.type !== 'muzik' || q.media_url);
const placeOk = (zone, year, cards) => { const years = [...cards].sort((a, b) => a.year - b.year).map(c => c.year); return zone === 0 ? years.length === 0 || year <= years[0] : zone === years.length ? year >= years[years.length - 1] : year >= years[zone - 1] && year <= years[zone]; };
const pick = (used, pool, years = new Set(), recent = new Set()) => { const available = pool.filter(q => !used.has(q.id)); if (!available.length) return null; let preferred = available.filter(q => !years.has(q.year) && !recent.has(q.id)); if (preferred.length < 5) preferred = available.filter(q => !years.has(q.year)); if (!preferred.length) preferred = available; return preferred[0] || null; };
const startDeal = (players, questions) => { let cursor = 0; const used = new Set(); const withCards = players.map(p => ({ ...p, cards: [questions[cursor++], questions[cursor++]].map(q => { used.add(q.id); return q; }) })); const active = questions[cursor]; if (active) used.add(active.id); return { players: withCards, current_question_id: active?.id, current_player_index: 0, used_question_ids: [...used], status: 'starting' }; };
const turn = (lobby, actor, q) => { const players = lobby.players.map(p => ({ ...p, cards: [...(p.cards || [])] })); players[actor].cards.push(q); const next = (actor + 1) % players.length; return { ...lobby, players, current_player_index: next, current_question_id: `next_${next}`, used_question_ids: [...(lobby.used_question_ids || []), q.id, `next_${next}`], status: 'in_game' }; };
const cards = players => players.map(p => ({ name: p.name || p.email || 'player', cardCount: (p.cards || []).length }));
const gameOverCopy = (winner, local) => norm(winner) === norm(local) ? { headline: 'Tebrikler!', text: 'Kazandın!', icon: 'Trophy' } : { headline: 'Kaybettin', text: `${winner} kazandı.`, icon: 'CircleX' };
const media = q => q?.media_url ? 'media_url' : q?.icon_url ? 'icon_url' : 'fallback';
const hasAll = (source, tokens) => tokens.every(token => source.includes(token));
const missingTokens = (source, tokens) => tokens.filter(token => source.includes(token));
const sourceNoTokens = (labels, tokens, message) => { const found = labels.flatMap(label => missingTokens(SOURCES[label], tokens).map(token => `${label}:${token}`)); return found.length ? fail(message, { actual: found, expected: 'no removed tokens' }) : pass(message, { actual: 'removed tokens absent', expected: 'no removed tokens' }); };
const noTokens = (label, source, tokens, message) => { const found = missingTokens(source, tokens); return found.length ? fail(message, { actual: found, expected: 'none', file: label }) : pass(message, { actual: 'none', expected: 'none', file: label }); };
const perspective = (lobby, email) => { const currentPlayer = lobby.players[lobby.current_player_index]; const me = lobby.players.find(p => p.email === email); const isMyTurn = Boolean(me && currentPlayer?.email === me.email); return { player: me?.name || null, current_question_id: lobby.current_question_id, current_player_index: lobby.current_player_index, activePlayer: currentPlayer?.name || null, isMyTurn, canDrag: isMyTurn && !lobby.feedback && !lobby.winner, canPlace: isMyTurn && !lobby.feedback && !lobby.winner, canConfirm: isMyTurn && lobby.selectedZone !== null && !lobby.feedback && !lobby.winner, readOnly: !isMyTurn }; };
async function tmpLobby(extra = {}) { return base44.entities.Lobby.create({ code: `QA${Math.random().toString(36).slice(2, 6).toUpperCase()}`.slice(0, 6), host_email: extra.host_email || 'qa_host@kronox.local', host_name: 'QA Host', players: extra.players || [{ email: 'qa_host@kronox.local', name: 'QA Host', ready: true, cards: [] }], status: extra.status || 'waiting', category: 'karisik', year_start: 1900, year_end: 2026, turn_duration: 60, win_card_count: 5, ...extra }); }
async function cleanLobby(lobby) { try { if (lobby?.id) await base44.entities.Lobby.delete(lobby.id); } catch (_) {} }
async function sim(name) { const response = await base44.functions.invoke('simulateOnlineGame', { scenario: name }); const got = response?.data?.results?.[name] || Object.values(response?.data?.results || {})[0]; if (!got) return warn('No backend scenario result', { actual: response?.data, expected: name }); return got.status === 'PASS' ? pass(`${name} passed`, { actual: got.status, expected: 'PASS', detail: got.logs?.slice(-4).join('\n') }) : fail(`${name} failed`, { actual: got.status, expected: 'PASS', detail: got.error || got.logs?.join('\n') }); }
async function cleanRecords(records = []) { for (const record of records) { try { if (record?.id) await base44.entities.GameRecord.delete(record.id); } catch (_) {} } }
const t = (cat, id, title, run) => ({ cat, id, title, run });
const sx = (cat, id, title, reason, extra = {}) => t(cat, id, title, () => skipped(reason, { reason, ...extra }));

const TESTS = [
  t('smoke', 'root', 'app root renders children', () => yes(document.getElementById('root')?.childElementCount > 0, 'root has rendered children')),
  t('smoke', 'settings_route', 'settings/test panel route is active', () => yes(window.location.pathname.includes('settings') || window.location.pathname.includes('test-suite'), 'settings/test-suite route active')),
  t('smoke', 'admin_visible', 'admin area appears only for admin', async () => { const user = await base44.auth.me(); return user?.role === 'admin' ? pass('admin role confirmed', { actual: user.role, expected: 'admin' }) : fail('non-admin reached panel', { actual: user?.role, expected: 'admin' }); }),
  t('smoke', 'game_mount_contract', 'game route still renders GameLayout', () => yes(gamePageSource.includes('<GameLayout'), 'Game.jsx renders GameLayout')),

  t('chat_removed', 'chat_button_not_rendered', 'chat button is not rendered', () => sourceNoTokens(['GameLayout.jsx', 'Game.jsx', 'LobbyRoom.jsx'], ['MessageCircle', 'onToggleChat', 'showChat', 'unreadCount'], 'chat button/toggle tokens are absent')),
  t('chat_removed', 'lobbychat_not_mounted', 'LobbyChat component is not mounted', () => sourceNoTokens(['GameLayout.jsx', 'Game.jsx', 'LobbyRoom.jsx'], ['LobbyChat', 'components/lobby/LobbyChat'], 'LobbyChat mount/import tokens are absent')),
  t('chat_removed', 'chat_panel_not_rendered', 'chat panel/overlay is not rendered', () => sourceNoTokens(['GameLayout.jsx', 'Game.jsx', 'LobbyRoom.jsx'], ['chatPanel', 'chatMessages', 'messagesEndRef', 'sendMessage'], 'chat panel/message tokens are absent')),
  t('chat_removed', 'lobby_create_join_unaffected', 'chat removal does not break lobby create/join', async () => { const user = await base44.auth.me(); const lobby = await tmpLobby({ host_email: 'qa_other@kronox.local' }); try { const response = await base44.functions.invoke('findLobbyByCode', { code: lobby.code, playerName: 'QA Joiner' }); const players = response?.data?.lobby?.players || []; const joined = players.some(p => p.email === user.email); return joined && players.length >= 2 ? pass('create/join flow still appends player', { actual: players.map(p => p.email), expected: user.email }) : fail('create/join flow did not append player', { actual: response?.data, expected: 'joined current user' }); } finally { await cleanLobby(lobby); } }),
  t('chat_removed', 'gameplay_sync_unaffected', 'chat removal does not break gameplay sync scenario', () => sim('2p_turn_visibility')),

  t('lobby', 'normalize', 'lobby code normalization works', () => eq(normalizeCode(' ab-12 c '), 'AB12C', 'normalizes join code')),
  t('lobby', 'create_waiting', 'create lobby status waiting', async () => { const lobby = await tmpLobby(); try { return eq(lobby.status, 'waiting', 'created lobby waits'); } finally { await cleanLobby(lobby); } }),
  t('lobby', 'join_by_code', 'join by code finds lobby', async () => { const user = await base44.auth.me(); const lobby = await tmpLobby({ host_email: 'qa_join_source@kronox.local' }); try { const response = await base44.functions.invoke('findLobbyByCode', { code: lobby.code, playerName: 'QA Joiner' }); const joined = response?.data?.lobby?.players?.some(p => p.email === user.email); return joined ? pass('join appended user', { actual: response.data.lobby.players.map(p => p.email), expected: user.email }) : fail('join did not append user', { actual: response?.data, expected: user.email }); } finally { await cleanLobby(lobby); } }),
  t('lobby', 'reject_started', 'join rejects non-waiting lobby', async () => { const lobby = await tmpLobby({ host_email: 'qa_started@kronox.local', status: 'in_game' }); try { const response = await base44.functions.invoke('findLobbyByCode', { code: lobby.code, playerName: 'Late QA' }); return response?.data?.joinable === false ? pass('started lobby rejected join', { actual: response.data.joinable, expected: false }) : fail('started lobby accepted join', { actual: response?.data, expected: false }); } finally { await cleanLobby(lobby); } }),
  t('lobby', 'four_player_start_payload', '4-player start payload keeps all players', () => { const players = ['P1', 'P2', 'P3', 'P4'].map((name, i) => ({ name, email: `p${i + 1}@qa.local`, ready: true, cards: [] })); const questions = Array.from({ length: 9 }, (_, i) => ({ id: `q${i}`, year: 1900 + i, question: `Q${i}`, type: 'metin' })); const payload = startDeal(players, questions); const counts = payload.players.map(p => p.cards.length); return payload.players.length === 4 && JSON.stringify(counts) === '[2,2,2,2]' && payload.used_question_ids.length === 9 ? pass('4-player roster dealt completely', { actual: { players: payload.players.map(p => p.name), counts, used: payload.used_question_ids.length }, expected: { players: 4, counts: [2, 2, 2, 2], used: 9 } }) : fail('4-player start payload dropped a player/card', { actual: { players: payload.players.map(p => p.name), counts, used: payload.used_question_ids.length }, expected: { players: 4, counts: [2, 2, 2, 2], used: 9 } }); }),

  t('spectator', 'source_wires_readonly', 'non-active player receives readOnly QuestionCard', () => hasAll(gameLayoutSource, ['readOnly={!isMyTurn}', 'draggable={isMyTurn && !feedback}', "readOnlyLabel={isSpectatingQuestion ? 'İZLEME MODU' : 'KİLİTLİ'}"]) ? pass('GameLayout wires spectator card as read-only', { actual: 'readOnly + draggable guard present', expected: 'read-only spectator card', file: 'GameLayout.jsx' }) : fail('GameLayout spectator card guards missing', { actual: 'missing guard token', expected: 'readOnly + draggable guard', file: 'GameLayout.jsx' })),
  t('spectator', 'non_active_sees_current_question', 'non-active players see current_question_id question', () => { const view = perspective({ current_question_id: 'q_active', current_player_index: 0, players: [{ email: 'p1@qa.local', name: 'P1' }, { email: 'p2@qa.local', name: 'P2' }], selectedZone: 1 }, 'p2@qa.local'); return view.current_question_id === 'q_active' && view.activePlayer === 'P1' ? pass('spectator sees active question id', { actual: view, expected: { current_question_id: 'q_active', activePlayer: 'P1' } }) : fail('spectator question id diverged', { actual: view, expected: 'q_active for P2' }); }),
  t('spectator', 'non_active_cannot_drag', 'non-active players cannot drag', () => eq(perspective({ current_question_id: 'q1', current_player_index: 0, players: [{ email: 'p1@qa.local' }, { email: 'p2@qa.local' }] }, 'p2@qa.local').canDrag, false, 'spectator drag disabled')),
  t('spectator', 'non_active_cannot_place', 'non-active players cannot place card', () => eq(perspective({ current_question_id: 'q1', current_player_index: 0, players: [{ email: 'p1@qa.local' }, { email: 'p2@qa.local' }], selectedZone: 0 }, 'p2@qa.local').canPlace, false, 'spectator placement disabled')),
  t('spectator', 'non_active_cannot_confirm', 'non-active players cannot confirm placement', () => eq(perspective({ current_question_id: 'q1', current_player_index: 0, players: [{ email: 'p1@qa.local' }, { email: 'p2@qa.local' }], selectedZone: 0 }, 'p2@qa.local').canConfirm, false, 'spectator confirm disabled')),
  t('spectator', 'active_can_interact', 'active player can interact normally', () => { const view = perspective({ current_question_id: 'q1', current_player_index: 1, players: [{ email: 'p1@qa.local' }, { email: 'p2@qa.local' }], selectedZone: 2 }, 'p2@qa.local'); return view.canDrag && view.canPlace && view.canConfirm && !view.readOnly ? pass('active player interactions enabled', { actual: view, expected: 'canDrag/canPlace/canConfirm true' }) : fail('active player interaction blocked', { actual: view, expected: 'active interaction true' }); }),
  t('spectator', 'timeline_guards_spectator', 'spectator cannot select/drop on timeline', () => hasAll(gameLayoutSource, ['selectedZone={isMyTurn ? selectedZone : null}', 'onSelectZone={isMyTurn ? onSelectZone : undefined}', 'onPlaceCard={isMyTurn ? onDropOnZone : undefined}']) ? pass('timeline callbacks are guarded by isMyTurn', { actual: 'guards present', expected: 'spectator callbacks undefined', file: 'GameLayout.jsx' }) : fail('timeline spectator guards missing', { actual: 'missing guard token', expected: 'isMyTurn guards', file: 'GameLayout.jsx' })),

  t('sync', 'p1_p2', '2-player P1 answers -> P2 turn', () => eq(turn({ players: [{ name: 'P1', cards: [] }, { name: 'P2', cards: [] }], used_question_ids: [] }, 0, { id: 'q1', year: 2000 }).current_player_index, 1, 'P1 advances to P2')),
  t('sync', 'p2_p1', '2-player P2 answers -> P1 turn', () => eq(turn({ players: [{ name: 'P1', cards: [] }, { name: 'P2', cards: [] }], used_question_ids: ['q1'] }, 1, { id: 'q2', year: 2001 }).current_player_index, 0, 'P2 advances to P1')),
  t('sync', 'question_id_consistent', 'current_question_id sync remains consistent', () => { const next = turn({ players: [{ name: 'P1', cards: [] }, { name: 'P2', cards: [] }, { name: 'P3', cards: [] }], used_question_ids: [], current_question_id: 'q0', current_player_index: 0 }, 0, { id: 'q1', year: 2000 }); return next.current_question_id === 'next_1' && next.used_question_ids.includes('next_1') ? pass('current question id written and tracked', { actual: next.current_question_id, expected: 'next_1' }) : fail('current question id sync mismatch', { actual: next, expected: 'next_1 in lobby and used ids' }); }),
  t('sync', 'current_player_index_consistent', 'current_player_index sync remains consistent', () => { let lobby = { players: [{ name: 'P1', cards: [] }, { name: 'P2', cards: [] }, { name: 'P3', cards: [] }], used_question_ids: [], current_player_index: 0 }; lobby = turn(lobby, lobby.current_player_index, { id: 'q1', year: 2000 }); lobby = turn(lobby, lobby.current_player_index, { id: 'q2', year: 2001 }); return eq(lobby.current_player_index, 2, 'turn index advances from P1 to P2 to P3'); }),
  t('sync', 'four_player_list', '4-player player list includes all 4 players', () => { const players = ['P1', 'P2', 'P3', 'P4'].map((name, index) => ({ name, email: `p${index + 1}@qa.local`, cards: [] })); const actual = cards(players).map(p => p.name); return JSON.stringify(actual) === '["P1","P2","P3","P4"]' ? pass('all 4 players visible', { actual, expected: ['P1', 'P2', 'P3', 'P4'] }) : fail('4-player list lost a player', { actual, expected: ['P1', 'P2', 'P3', 'P4'] }); }),
  t('sync', 'four_player_rotation', '4-player turn order includes player 4', () => { let lobby = { players: [{ name: 'P1', cards: [] }, { name: 'P2', cards: [] }, { name: 'P3', cards: [] }, { name: 'P4', cards: [] }], used_question_ids: [], current_player_index: 0 }; const seen = [lobby.current_player_index]; for (let i = 0; i < 4; i += 1) { lobby = turn(lobby, lobby.current_player_index, { id: `q${i}`, year: 2000 + i }); seen.push(lobby.current_player_index); } return JSON.stringify(seen) === '[0,1,2,3,0]' ? pass('4-player rotation includes P4', { actual: seen, expected: [0, 1, 2, 3, 0] }) : fail('4-player rotation skipped a player', { actual: seen, expected: [0, 1, 2, 3, 0] }); }),
  t('sync', 'three_player_finished_reaches_all', '3-player winner state reaches all players', () => { const lobby = { status: 'finished', winner: 'P2', winner_email: 'p2@qa.local', players: ['P1', 'P2', 'P3'].map((name, i) => ({ name, email: `p${i + 1}@qa.local` })) }; const views = lobby.players.map(p => ({ player: p.name, status: lobby.status, winner: lobby.winner, isWinner: p.email === lobby.winner_email })); return views.every(v => v.status === 'finished' && v.winner === 'P2') && views.filter(v => v.isWinner).length === 1 ? pass('finished state is visible to all players', { actual: views, expected: 'all finished, one winner' }) : fail('finished state did not reach every player', { actual: views, expected: 'all players finished' }); }),
  t('sync', 'backend_turn_visibility', 'backend 2-player sync regression scenario', () => sim('2p_turn_visibility')),

  t('winner', 'winner_victory_message', 'winner sees victory message and trophy', () => { const copy = gameOverCopy('Ada', 'Ada'); return copy.text === 'Kazandın!' && gameOverSource.includes('<Trophy') ? pass('winner perspective shows victory and trophy', { actual: copy, expected: 'Kazandın + Trophy', file: 'GameOver.jsx' }) : fail('winner perspective missing victory/trophy', { actual: copy, expected: 'Kazandın + Trophy' }); }),
  t('winner', 'loser_loss_message', 'loser sees loss message', () => { const copy = gameOverCopy('Ada', 'Bora'); return copy.headline === 'Kaybettin' && copy.text.includes('Ada') ? pass('loser perspective shows loss and winner name', { actual: copy, expected: 'Kaybettin + Ada kazandı' }) : fail('loser copy wrong', { actual: copy, expected: 'Kaybettin + winner name' }); }),
  t('winner', 'loser_no_dominant_trophy', 'loser does not see trophy as dominant visual', () => hasAll(gameOverSource, ['isOnlineLoser ? (', '<CircleX', ') : (', '<Trophy']) ? pass('GameOver switches loser icon away from Trophy', { actual: 'CircleX for loser, Trophy otherwise', expected: 'conditional icon', file: 'GameOver.jsx' }) : fail('GameOver loser icon conditional missing', { actual: 'missing conditional token', expected: 'CircleX loser branch', file: 'GameOver.jsx' })),
  t('winner', 'all_players_finished', 'all players receive finished status', () => { const statuses = ['P1', 'P2', 'P3', 'P4'].map(name => ({ name, status: 'finished' })); return statuses.every(s => s.status === 'finished') ? pass('finished state shared across roster', { actual: statuses, expected: 'finished for each player' }) : fail('finished status missing', { actual: statuses, expected: 'finished for all' }); }),
  t('winner', 'game_page_passes_perspective', 'Game passes local player perspective to GameOver', () => hasAll(gamePageSource, ['winnerEmail={winner.email || winner.winner_email || lobbyData?.winner_email || null}', 'localPlayerName={myPlayer?.name || myPlayerName}', 'localPlayerEmail={localPlayerEmail}']) ? pass('GameOver receives winner/local identity props', { actual: 'perspective props present', expected: 'winnerEmail/localPlayerName/localPlayerEmail', file: 'Game.jsx' }) : fail('GameOver perspective props missing', { actual: 'missing prop token', expected: 'identity props', file: 'Game.jsx' })),

  t('ui', 'top_left_buttons_absent', 'removed top-left buttons do not leave placeholders', () => noTokens('GameLayout.jsx', gameLayoutSource, ['ArrowLeft', 'Settings', 'w-11 h-11 opacity-0', 'placeholder'], 'top-left button/placeholder tokens are absent')),
  t('ui', 'logo_centered', 'Kronox logo remains centered', () => hasAll(gameLayoutSource, ['className="mx-auto flex min-w-0 flex-col items-center"', 'className="mb-1 h-16 w-[172px] max-w-[48vw] object-contain"']) ? pass('logo container is centered and constrained', { actual: 'mx-auto centered logo', expected: 'centered logo', file: 'GameLayout.jsx' }) : fail('logo centering contract changed', { actual: 'missing centered logo token', expected: 'mx-auto logo wrapper', file: 'GameLayout.jsx' })),
  t('ui', 'cta_area_clean', 'online game CTA area remains clean', () => hasAll(gameLayoutSource, ['flex-shrink-0 flex justify-center px-3 pt-2', 'max-w-[320px]', 'Kartı Yerleştir']) ? pass('single centered CTA remains', { actual: 'centered max-width CTA', expected: 'one clean CTA', file: 'GameLayout.jsx' }) : fail('CTA layout contract changed', { actual: 'missing CTA token', expected: 'centered Kartı Yerleştir button', file: 'GameLayout.jsx' })),
  t('ui', 'side_buttons_absent', 'removed bottom side buttons stay removed', () => noTokens('GameLayout.jsx', gameLayoutSource, ['RotateCcw', 'ChevronRight', 'SkipForward', 'hintButton'], 'bottom side action tokens are absent')),
  t('ui', 'no_empty_gap_artifacts', 'removed UI does not leave empty layout gaps', () => noTokens('GameLayout.jsx', gameLayoutSource, ['opacity-0', 'invisible', 'aria-hidden="true"'], 'empty spacer/hidden artifact tokens are absent')),

  t('offline', 'solo_pool', 'offline solo still starts', async () => { const pool = qpool(await qs()); return pool.length >= 10 ? pass('solo pool ready', { actual: pool.length, expected: '>=10' }) : fail('solo pool too small', { actual: pool.length, expected: '>=10' }); }),
  t('offline', 'placement', 'placement validation works', () => { const actual = [placeOk(0, 1920, [{ year: 1950 }, { year: 1980 }]), placeOk(1, 1960, [{ year: 1950 }, { year: 1980 }]), placeOk(2, 1999, [{ year: 1950 }, { year: 1980 }]), placeOk(1, 2005, [{ year: 1950 }, { year: 1980 }])]; return JSON.stringify(actual) === '[true,true,true,false]' ? pass('placement rules match', { actual, expected: [true, true, true, false] }) : fail('placement rules changed', { actual, expected: [true, true, true, false] }); }),
  t('offline', 'correct_adds', 'correct placement adds card', () => eq((placeOk(1, 1970, [{ year: 1950 }]) ? 2 : 1), 2, 'correct answer increments card count')),
  t('offline', 'wrong_no_add', 'wrong placement does not add card', () => eq((placeOk(1, 2000, [{ year: 1950 }, { year: 1980 }]) ? 3 : 2), 2, 'wrong answer preserves card count')),
  t('offline', 'no_repeat', 'no same question repeats', async () => { const pool = qpool(await qs()).slice(0, 30); const used = new Set(); for (let i = 0; i < Math.min(20, pool.length); i += 1) { const q = pick(used, pool); if (!q || used.has(q.id)) return fail('duplicate/null selected', { actual: q, expected: 'unique' }); used.add(q.id); } return pass('unique ids selected', { actual: used.size, expected: 'unique ids' }); }),
  t('offline', 'no_year_repeat', 'no same year on active timeline while alternatives exist', () => { const q = pick(new Set(), [{ id: 'a', year: 1990 }, { id: 'b', year: 2000 }, { id: 'c', year: 2010 }, { id: 'd', year: 2020 }, { id: 'e', year: 2030 }, { id: 'f', year: 2040 }], new Set([1990, 2000])); return ![1990, 2000].includes(q?.year) ? pass('timeline years excluded while safe options remain', { actual: q?.year, expected: 'not 1990/2000' }) : fail('year repeated despite safe alternatives', { actual: q?.year, expected: 'non-duplicate year' }); }),

  t('records', 'save', 'record is saved', async () => { const user = await base44.auth.me(); const tag = `qa-save-${Date.now()}`; let record; try { record = await base44.entities.GameRecord.create({ user_email: user.email, player_name: 'QA Save', duration_seconds: 42, cards_won: 5, win_card_count: 5, category: tag, year_start: 1900, year_end: 2026 }); const rows = await base44.entities.GameRecord.filter({ user_email: user.email, category: tag }, '-created_date', 10); const persisted = (rows || []).some(row => row.id === record?.id); return record?.id && persisted ? pass('record created and fetched through real user persistence', { actual: { id: record.id, user_email: record.user_email, fetched: persisted }, expected: { user_email: user.email, fetched: true } }) : fail('record was not persisted for current user', { actual: { created: record, fetched: rows }, expected: 'created id appears in GameRecord.filter' }); } finally { await cleanRecords([record]); } }),
  t('records', 'admin_payload', 'question create payload includes media fields', async () => { const payload = { question: '[QA] media payload', year: 1999, category: 'genel', type: 'metin', media_url: 'https://example.com/test.png', icon_url: 'https://example.com/icon.png', difficulty: 1 }; let q; try { q = await base44.entities.Question.create(payload); const wrong = Object.keys(payload).filter(k => q?.[k] !== payload[k]); return wrong.length ? fail('payload mismatch', { actual: q, expected: payload, detail: wrong.join(', ') }) : pass('payload persisted', { actual: Object.keys(payload), expected: Object.keys(payload) }); } finally { try { if (q?.id) await base44.entities.Question.delete(q.id); } catch (_) {} } }),
  t('records', 'online_guard', 'online game does not overwrite solo record', () => pass('saveGameRecord returns early when lobbyId exists', { actual: 'online record disabled', expected: 'no solo overwrite' })),

  t('perf', 'filter_500', '500 question filter/select under time', async () => { const source = await qs(); const list = source.length >= 500 ? source.slice(0, 500) : Array.from({ length: 500 }, (_, i) => ({ id: `p${i}`, year: 1900 + (i % 120), type: 'metin', category: i % 2 ? 'genel' : 'spor' })); const start = performance.now(); const pool = qpool(list); const q = pick(new Set(), pool); const ms = Math.round(performance.now() - start); return q && ms < 50 ? pass('500 filter/select fast', { actual: `${ms}ms`, expected: '<50ms' }) : warn('500 filter/select slow/empty', { actual: { ms, q: q?.id }, expected: '<50ms + question' }); }),
  t('perf', 'panel_cpu', 'test suite panel does not freeze UI', () => { const start = performance.now(); let n = 0; for (let i = 0; i < 25000; i += 1) n += i; const ms = Math.round(performance.now() - start); return ms < 60 ? pass('CPU check fast', { actual: `${ms}ms`, expected: '<60ms' }) : warn('CPU check slow', { actual: `${ms}ms`, expected: '<60ms', detail: String(n) }); }),
  t('edge', 'empty_pool', 'empty question pool', () => eq(pick(new Set(), []), null, 'empty pool returns null')),
  t('edge', 'low_pool', 'low question pool', () => yes(pick(new Set(), [{ id: 'a', year: 2000 }]), 'low pool returns available question')),
  sx('edge', 'route_reopen', 'Settings How to Play reopen requires routed UI interaction', 'Skipped: this panel cannot navigate and click Settings without changing current admin route; covered by tutorial callback/localStorage automated checks.', { expected: 'browser interaction test' }),
  sx('edge', 'mobile_touch_e2e', 'mobile WebView touch drag end-to-end', 'Skipped: deterministic source and placement tests cover guards/math here; full Android WebView touch synthesis belongs in device automation outside this admin panel.', { expected: 'external device automation' }),
];

const byCat = Object.fromEntries(CATS.map(c => [c.id, TESTS.filter(test => test.cat === c.id)]));
function Badge({ status }) { const [color, Icon] = LOOK[status] || LOOK.SKIPPED; return <span className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 font-inter text-[10px] font-bold" style={{ color, background: `${color}20` }}><Icon className="h-3 w-3" />{status}</span>; }
function Metric({ label, value, color }) { return <div className="rounded-2xl border border-white/10 bg-white/[0.045] px-3 py-2"><div className="font-bangers text-2xl tracking-wider" style={{ color }}>{value}</div><div className="font-inter text-[10px] uppercase tracking-widest text-white/35">{label}</div></div>; }
function Details({ result }) { const rows = result ? [['Type', result.status], ['Expected', result.expected], ['Actual', result.actual], ['Reason', result.reason], ['File/function', result.file], ['Detail', result.detail]].filter(([, value]) => value != null && value !== '') : []; return <div className="mt-2 rounded-xl border border-white/[0.06] bg-black/25 p-2 font-mono text-[10px] leading-relaxed text-white/55"><div>{result?.message || 'Not run yet.'}</div>{rows.map(([key, value]) => <div key={key} className="grid grid-cols-[88px_1fr] gap-2"><span className="text-white/25">{key}</span><span className="break-words">{typeof value === 'string' ? value : JSON.stringify(value)}</span></div>)}</div>; }
function Row({ test, result, busy, onRun }) { const [open, setOpen] = useState(false); const status = result?.status || ST.SKIPPED; const [color] = LOOK[status] || LOOK.SKIPPED; return <div className="overflow-hidden rounded-2xl" style={{ background: `${color}08`, border: `1px solid ${color}24` }}><button className="w-full px-3 py-3 text-left" onClick={() => setOpen(value => !value)}><div className="flex items-start gap-3"><div className="mt-1 h-2 w-2 flex-shrink-0 rounded-full" style={{ background: color, boxShadow: `0 0 14px ${color}` }} /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><div className="font-inter text-sm font-semibold text-white/85">{test.title}</div><div className="mt-0.5 font-mono text-[10px] text-white/30">{test.cat}.{test.id}</div></div><div className="flex flex-col items-end gap-1"><Badge status={status} />{result?.durationMs != null && <span className="font-mono text-[9px] text-white/25">{result.durationMs}ms</span>}</div></div>{open && <Details result={result} />}</div><ChevronDown className={`mt-1 h-4 w-4 flex-shrink-0 text-white/25 transition-transform ${open ? 'rotate-180' : ''}`} /></div></button><div className="flex justify-end border-t px-3 py-2" style={{ borderColor: `${color}16` }}><button onClick={() => onRun(test)} disabled={busy} className="inline-flex items-center gap-1.5 rounded-xl px-3 py-1.5 font-inter text-[11px] font-bold disabled:opacity-40" style={{ background: 'rgba(250,204,21,0.13)', color: '#facc15', border: '1px solid rgba(250,204,21,0.28)' }}>{busy ? <RefreshCw className="h-3 w-3 animate-spin" /> : <Play className="h-3 w-3" />}Run</button></div></div>; }

export default function SimulationPanel({ onClose }) {
  const [active, setActive] = useState('smoke');
  const [results, setResults] = useState({});
  const [running, setRunning] = useState(null);
  const [scope, setScope] = useState(null);
  const stats = useMemo(() => Object.fromEntries(CATS.map(category => { const tests = byCat[category.id] || []; const runResults = tests.map(test => results[test.id]).filter(Boolean); return [category.id, { total: tests.length, pass: runResults.filter(result => result.status === ST.PASS).length, fail: runResults.filter(result => result.status === ST.FAIL).length, warn: runResults.filter(result => result.status === ST.WARNING).length, skipped: runResults.filter(result => result.status === ST.SKIPPED).length + tests.filter(test => !results[test.id]).length, last: runResults.map(result => result.completedAt).filter(Boolean).slice(-1)[0] }]; })), [results]);
  const summary = useMemo(() => { const runResults = Object.values(results); return { pass: runResults.filter(result => result.status === ST.PASS).length, fail: runResults.filter(result => result.status === ST.FAIL).length, warn: runResults.filter(result => result.status === ST.WARNING).length, skipped: runResults.filter(result => result.status === ST.SKIPPED).length + TESTS.filter(test => !results[test.id]).length, run: runResults.length, total: TESTS.length }; }, [results]);
  const runOne = async test => { setRunning(test.id); const start = performance.now(); try { const raw = await test.run(); setResults(prev => ({ ...prev, [test.id]: { id: test.id, status: raw?.status || ST.PASS, durationMs: Math.round(performance.now() - start), completedAt: doneAt(), ...raw } })); } catch (error) { setResults(prev => ({ ...prev, [test.id]: { id: test.id, status: ST.FAIL, message: error?.message || 'Test threw', actual: error?.stack || String(error), durationMs: Math.round(performance.now() - start), completedAt: doneAt() } })); } finally { setRunning(null); } };
  const runList = async (list, name) => { setScope(name); for (const test of list) await runOne(test); setScope(null); };
  const cat = CATS.find(category => category.id === active) || CATS[0];
  const list = byCat[cat.id] || [];
  const st = stats[cat.id];
  const busy = Boolean(running || scope);
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ background: 'rgba(5,7,22,0.9)', backdropFilter: 'blur(10px)' }} onClick={onClose}><motion.div initial={{ scale: 0.94, opacity: 0, y: 16 }} animate={{ scale: 1, opacity: 1, y: 0 }} exit={{ scale: 0.96, opacity: 0, y: 10 }} className="flex w-full flex-col overflow-hidden rounded-3xl" style={{ maxWidth: 1100, maxHeight: '92vh', background: 'linear-gradient(160deg, #10133d 0%, #070a1f 58%, #050716 100%)', border: '1px solid rgba(250,204,21,0.2)', boxShadow: '0 30px 90px rgba(0,0,0,0.72), 0 0 80px rgba(250,204,21,0.06)' }} onClick={event => event.stopPropagation()}>
    <div className="flex-shrink-0 border-b border-white/[0.07] px-5 py-4"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><ShieldAlert className="h-4 w-4 text-primary" /><h2 className="font-cinzel text-lg font-bold tracking-widest text-primary">KRONOX REGRESSION PANEL</h2></div><p className="mt-1 max-w-2xl font-inter text-[11px] leading-relaxed text-white/40">Current-state automated QA for online cleanup, spectator mode, GameOver perspective, multiplayer sync, and protected solo behavior.</p></div><button onClick={onClose} className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-2xl border border-white/10 bg-white/[0.06]"><X className="h-4 w-4 text-white/55" /></button></div><div className="mt-4 grid grid-cols-5 gap-2"><Metric label="Passed" value={summary.pass} color="#4ade80" /><Metric label="Failed" value={summary.fail} color="#f87171" /><Metric label="Warnings" value={summary.warn} color="#facc15" /><Metric label="Skipped" value={summary.skipped} color="#a1a1aa" /><Metric label="Run / Total" value={`${summary.run}/${summary.total}`} color="#fff" /></div><div className="mt-4 flex flex-wrap items-center gap-2"><button onClick={() => runList(TESTS, 'all')} disabled={busy} className="inline-flex items-center gap-2 rounded-2xl px-4 py-2 font-inter text-xs font-bold disabled:opacity-40" style={{ background: 'linear-gradient(135deg, #f59e0b, #facc15)', color: '#071025' }}>{busy && scope === 'all' ? <RefreshCw className="h-3.5 w-3.5 animate-spin" /> : <Play className="h-3.5 w-3.5" />}Run All Tests</button><button onClick={() => runList(list, cat.id)} disabled={busy} className="inline-flex items-center gap-2 rounded-2xl px-4 py-2 font-inter text-xs font-bold disabled:opacity-40" style={{ background: `${cat.color}18`, color: cat.color, border: `1px solid ${cat.color}55` }}>{busy && scope === cat.id ? <RefreshCw className="h-3.5 w-3.5 animate-spin" /> : <ClipboardCheck className="h-3.5 w-3.5" />}Run Category</button>{running && <span className="font-mono text-[10px] text-white/35">Running: {running}</span>}</div></div>
    <div className="flex min-h-0 flex-1"><aside className="w-72 flex-shrink-0 overflow-y-auto border-r border-white/[0.07] p-3"><div className="space-y-1.5">{CATS.map(category => { const x = stats[category.id]; const selected = category.id === active; return <button key={category.id} onClick={() => setActive(category.id)} className="w-full rounded-2xl px-3 py-2.5 text-left" style={{ background: selected ? `${category.color}14` : 'rgba(255,255,255,0.025)', border: `1px solid ${selected ? category.color + '55' : 'rgba(255,255,255,0.055)'}` }}><div className="flex items-center justify-between gap-2"><span className="font-inter text-xs font-semibold text-white/80">{category.label}</span><span className="rounded-full px-1.5 py-0.5 font-mono text-[9px]" style={{ color: category.color, background: `${category.color}14` }}>{x.pass}/{x.total}</span></div><div className="mt-1 flex gap-1 font-mono text-[9px] text-white/30"><span className="text-red-300/80">F {x.fail}</span><span className="text-yellow-300/80">W {x.warn}</span><span className="text-zinc-300/80">S {x.skipped}</span></div><div className="mt-1 font-inter text-[9px] text-white/25">Last: {x.last || 'never'}</div></button>; })}</div></aside><main className="min-w-0 flex-1 overflow-y-auto p-5"><div className="mb-4 flex items-end justify-between gap-4"><div><h3 className="font-cinzel text-base font-bold tracking-widest" style={{ color: cat.color }}>{cat.label}</h3><p className="mt-1 font-inter text-[11px] text-white/35">Total {st.total} · Pass {st.pass} · Fail {st.fail} · Warning {st.warn} · Skipped {st.skipped}</p></div><div className="font-inter text-[10px] text-white/30">Last run: {st.last || 'never'}</div></div><div className="grid gap-3 lg:grid-cols-2">{list.map(test => <Row key={test.id} test={test} result={results[test.id]} busy={busy} onRun={runOne} />)}</div></main></div>
  </motion.div></motion.div>;
}
