import adminSource from '../../pages/AdminPage.jsx?raw';
import appSource from '../../App.jsx?raw';
import panelSource from '../admin/ReleaseReadinessTool.jsx?raw';
import healthSource from '../admin/ReleaseHealthSummary.jsx?raw';
import deploySource from '../admin/ReleaseDeployabilitySummary.jsx?raw';
import linksSource from '../admin/ReleaseProofLinks.jsx?raw';
import securitySource from '../admin/ReleaseSecuritySummary.jsx?raw';
import dataSource from '../../lib/releaseReadiness.js?raw';
import functionGateSource from '../../../scripts/checkBase44FunctionsCompile.mjs?raw';

const SUITE_ID = 'release_readiness_health';
const SUITE_NAME = 'Release Readiness Health Suite';
const pass = (reason) => ({ status: 'PASS', reason, verification: 'STATIC_CONTRACT' });
const fail = (reason, actual) => ({ status: 'FAIL', reason, actual, verification: 'STATIC_CONTRACT' });
const missing = (source, tokens) => tokens.filter((token) => !String(source || '').includes(token));
const present = (source, tokens) => tokens.filter((token) => String(source || '').includes(token));
const makeCase = (id, name, run) => ({ key: `${SUITE_ID}.${id}`, suiteId: SUITE_ID, suiteName: SUITE_NAME, id, name, critical: true, actionType: 'CODE_FIX', run });
const uiSource = `${panelSource}\n${healthSource}\n${deploySource}\n${linksSource}\n${securitySource}\n${dataSource}`;

export const EXTRA_SUITES = [{ id: SUITE_ID, name: SUITE_NAME, critical: true, color: '#fbbf24' }];
export const EXTRA_TESTS = [
  makeCase('release_panel_admin_only', 'Release panel is Admin-only', () => { const absent = missing(`${adminSource}\n${appSource}\n${panelSource}`, ['<AdminRoute><AdminPage', '<ReleaseReadinessTool />', 'data-admin-release-readiness="read-only"']); const exposed = present(appSource, ['path="/release-readiness"', 'path="/release-proof"']); return absent.length || exposed.length ? fail('Admin route isolation drifted.', { missing: absent, exposed }) : pass('Release readiness exists only inside guarded Admin Ekranı with no public route.'); }),
  makeCase('release_panel_read_only', 'Release panel is read-only', () => { const forbidden = present(uiSource, ['base44.', '.create(', '.update(', '.delete(', 'functions.invoke', 'deploy(', 'publish(']); const absent = missing(panelSource, ['data-release-mutation="none"', 'data-release-deployment="manual-only"', 'Durumlar kalıcı olarak yazılmaz']); return forbidden.length || absent.length ? fail('Panel can mutate or deploy.', { forbidden, missing: absent }) : pass('The panel has no data mutation, persistence, deploy, or publish path.'); }),
  makeCase('manual_proof_boundaries_are_explicit', 'Manual and external proof boundaries are explicit', () => { const absent = missing(uiSource, ['Üretim deploy', 'gerçek cihaz', 'RLS / çoklu hesap', 'VAPID üretim', 'Platform unique index', 'Harici', 'Manuel']); return absent.length ? fail('Manual boundaries are incomplete.', { missing: absent }) : pass('Deployment, devices, RLS, VAPID, and platform indexes remain manual/external.'); }),
  makeCase('no_secret_values_rendered', 'No secret values are rendered', () => { const forbidden = present(uiSource, ['process.env', 'import.meta.env', 'console.log', 'BEGIN PRIVATE KEY', 'KRONOX_ADMIN_EMAILS', 'google_oauth_client_secret', 'value={secret}']); return forbidden.length ? fail('Secret source/value rendering was detected.', { forbidden }) : pass('The panel renders safe requirement labels only and reads no environment or secret value.'); }),
  makeCase('function_count_gate_visible', 'Function-count and SDK gates are visible', () => { const absent = missing(`${uiSource}\n${functionGateSource}`, ['functionCount: 50', 'functionLimit: 50', 'MAX_BASE44_FUNCTIONS = 50', 'currentSdk', 'expectedSdk', 'Engelli']); return absent.length ? fail('Deployability gate visibility drifted.', { missing: absent }) : pass('The 50-function ceiling and current SDK compatibility blocker are visible.'); }),
  makeCase('full_health_not_faked', 'Full Health is not fabricated', () => { const absent = missing(uiSource, ['Canlı sonuç yok', 'Health PASS yayın kanıtı değildir', 'Koşum gerekli', 'Otomatik sözleşme kontrolü']); const fake = present(dataSource, ["status: 'Passed'", "status: 'PASS'"]); return absent.length || fake.length ? fail('Panel can imply an unproven Health pass.', { missing: absent, fake }) : pass('No live result means no PASS; targeted groups remain marked for execution.'); }),
  makeCase('device_webview_proof_checklist_present', 'Device and WebView checklist is present', () => { const absent = missing(dataSource, ['Android gerçek cihaz', 'iOS Safari / TestFlight / WebView', '320 / 360 / 390', 'Safe-area / BottomNav / modal', 'Düşük seviye Android']); return absent.length ? fail('Device proof checklist is incomplete.', { missing: absent }) : pass('Android, iOS/WebView, narrow widths, safe areas, and low-end performance are listed.'); }),
  makeCase('online_multi_account_proof_checklist_present', 'Online multi-account checklist is present', () => { const absent = missing(dataSource, ['İki hesapla davet akışı', 'Rastgele eşleşme ve kodla katılma', 'Backend ortak deste', 'Kazanan +15 / kaybeden -6', 'Yeniden bağlanma / iptal / zaman aşımı']); return absent.length ? fail('Online manual proof coverage is incomplete.', { missing: absent }) : pass('Invite, random, join, shared deck, score, and recovery checks are listed.'); }),
  makeCase('economy_daily_solo_proof_links_present', 'Economy, Daily, and Solo proof links are present', () => { const absent = missing(`${dataSource}\n${linksSource}`, ['Integrity Snapshot', 'Günlük Çark talebi', '7 günlük ödül 200 Elmas', 'Solo Streak +3 / +5', 'Mağaza Elmas harcamaları', 'idempotency']); return absent.length ? fail('Economy/Daily/Solo proof references are incomplete.', { missing: absent }) : pass('B1 Integrity plus Daily, Solo Streak, Store, and idempotency proof are linked/listed.'); }),
  makeCase('question_qa_proof_links_present', 'Question QA proof link is present', () => { const absent = missing(`${dataSource}\n${linksSource}`, ['Soru Kalite Raporu', 'Kategori dağılımı incelendi', 'Tekrar riski incelendi', 'Yıl / zorluk kalitesi', 'Manuel içerik onayı']); return absent.length ? fail('B3 Question QA linkage drifted.', { missing: absent }) : pass('The B3 panel and manual content approval steps are linked/listed.'); }),
  makeCase('no_public_private_id_exposure', 'Release UI exposes no private identifiers', () => { const forbidden = present(uiSource, ['{user.', '{row.email', '{row.id', 'guest_token}', 'owner_key}', 'actor_key_hash}', 'error.message']); return forbidden.length ? fail('Private value rendering was detected.', { forbidden }) : pass('The release UI is static/admin-only and renders no account rows, private IDs, raw errors, or secrets.'); }),
  makeCase('no_backend_function_count_growth', 'B4 adds no backend function', () => { const absent = missing(`${functionGateSource}\n${dataSource}`, ['MAX_BASE44_FUNCTIONS = 50', 'entryFiles.length > MAX_BASE44_FUNCTIONS', 'functionCount: 50']); const calls = present(panelSource, ['functions.invoke', 'functions.fetch']); return absent.length || calls.length ? fail('B4 function-count proof drifted.', { missing: absent, calls }) : pass('B4 is frontend/docs/Health-only and the deploy ceiling remains 50.'); }),
];