export const RUNTIME_E2E_SUITE_ID = 'runtime_e2e_automation_health';
export const RUNTIME_E2E_RUN_COMMAND = 'npm run health:e2e';
export const RUNTIME_E2E_REPORT_URL = '/health-e2e/latest.json';
export const RUNTIME_E2E_REPORT_STORAGE_KEY = 'kronox_runtime_e2e_last_report_v2';
export const RUNTIME_E2E_EXECUTION_SCOPE = Object.freeze({
  UI_ONLY: 'UI_ONLY',
  BACKEND_DEPENDENT: 'BACKEND_DEPENDENT',
});

function step(id, title, action, expected, options = {}) {
  return Object.freeze({
    id,
    title,
    action,
    expected,
    required: options.required !== false,
    selector: options.selector || null,
  });
}

function scenario({
  scenarioId,
  title,
  description,
  riskArea,
  maxExpectedDuration,
  requiredCapabilities,
  optionalCapabilities = [],
  executionScope,
  backendServices = [],
  testUserStrategy,
  steps,
  successCriteria,
  failureCategories,
  manualFallback,
}) {
  return Object.freeze({
    scenarioId,
    title,
    description,
    riskArea,
    maxExpectedDuration,
    requiredCapabilities: Object.freeze(requiredCapabilities),
    optionalCapabilities: Object.freeze(optionalCapabilities),
    executionScope,
    backendServices: Object.freeze(backendServices),
    testUserStrategy,
    steps: Object.freeze(steps),
    successCriteria: Object.freeze(successCriteria),
    failureCategories: Object.freeze(failureCategories),
    manualFallback,
  });
}

export const RUNTIME_E2E_SCENARIOS = Object.freeze([
  scenario({
    scenarioId: 'runtime_e2e.app_bootstrap_guest_home',
    title: 'App bootstrap + Guest Home',
    description: 'Opens a new browser context, waits for guest/auth bootstrap, and verifies a usable private-data-safe Home surface.',
    riskArea: 'startup_privacy',
    maxExpectedDuration: 45000,
    requiredCapabilities: ['browser', 'appDocument', 'appConfig', 'base44Backend', 'guestBootstrap', 'completedActor'],
    executionScope: RUNTIME_E2E_EXECUTION_SCOPE.BACKEND_DEPENDENT,
    backendServices: ['base_app', 'actor_bootstrap'],
    testUserStrategy: 'A fresh browser context uses KRONOX_E2E_STORAGE_STATE when supplied. A first-launch onboarding-only context is reported as a setup gap, never a fake Home PASS.',
    steps: [
      step('bootstrap.open', 'Open a fresh browser context', 'Navigate to the configured Kronox base URL.', 'The app document loads within the bounded timeout.', { selector: 'body' }),
      step('bootstrap.settle', 'Wait for app bootstrap', 'Wait for splash/auth/guest bootstrap to settle.', 'A Home or explicit onboarding/setup surface becomes visible.'),
      step('bootstrap.home', 'Verify Home', 'Locate the Home screen root.', 'The Home screen is visible.', { selector: '[data-testid="home-screen"]' }),
      step('bootstrap.play_cta', 'Verify primary play action', 'Locate the current OYNA / Solo action.', 'The primary play action is visible and enabled.', { selector: '[data-testid="home-solo-entry"]' }),
      step('bootstrap.bottom_nav', 'Verify BottomNav contract', 'Read the visible tab labels.', 'Exactly Ana Sayfa, Liderlik, and Profil are present.', { selector: '[data-testid="bottom-nav"]' }),
      step('bootstrap.public_safety', 'Scan public text safety', 'Inspect rendered public text for raw errors, stack traces, email, and private identity keys.', 'No private identifier or raw backend/debug output is rendered.'),
      step('bootstrap.interactive', 'Verify Home remains interactive', 'Focus and click a safe Home navigation control without mutation.', 'The app responds and remains usable.', { selector: '[data-testid="bottom-nav-home"]' }),
    ],
    successCriteria: ['Home is visible', 'Guest/test state is usable', 'No crash or private leak'],
    failureCategories: ['BOOTSTRAP_TIMEOUT', 'HOME_NOT_VISIBLE', 'PRIVATE_DATA_EXPOSURE', 'RAW_ERROR_EXPOSURE'],
    manualFallback: 'Complete guest onboarding or provide an isolated Playwright storage-state file, then rerun.',
  }),
  scenario({
    scenarioId: 'runtime_e2e.bottom_nav_route_sync',
    title: 'BottomNav route sync and root reset',
    description: 'Proves that committed route, visible content, and the three-tab active state remain synchronized, including Profile root reset.',
    riskArea: 'navigation',
    maxExpectedDuration: 45000,
    requiredCapabilities: ['browser', 'appDocument', 'uiOnly', 'completedActor'],
    executionScope: RUNTIME_E2E_EXECUTION_SCOPE.UI_ONLY,
    testUserStrategy: 'Uses the same isolated completed guest or authenticated storage state; it performs navigation only.',
    steps: [
      step('nav.home_active', 'Home tab is active', 'Start at Home and inspect aria-current.', 'Ana Sayfa is the only active tab.', { selector: '[data-testid="bottom-nav-home"]' }),
      step('nav.leaderboard', 'Open Leaderboard', 'Tap Liderlik.', 'Leaderboard content appears and Liderlik becomes active.', { selector: '[data-testid="bottom-nav-leaderboard"]' }),
      step('nav.profile', 'Open Profile', 'Tap Profil.', 'Profile content appears and Profil becomes active.', { selector: '[data-testid="bottom-nav-profile"]' }),
      step('nav.home_return', 'Return Home', 'Tap Ana Sayfa.', 'Home content appears and Ana Sayfa becomes active.', { selector: '[data-testid="bottom-nav-home"]' }),
      step('nav.profile_subroute', 'Open a Profile subroute', 'Open Profil, then Profil Bilgileri.', 'The Profile Edit root appears.', { selector: '[data-testid="profile-edit-entry"]' }),
      step('nav.profile_root_reset', 'Reset Profile root', 'Tap the already-owned Profil BottomNav tab from the subroute.', 'The committed route is /profile and the Profile root is visible.', { selector: '[data-testid="bottom-nav-profile"]' }),
      step('nav.leaderboard_root_reset', 'Reset Leaderboard root', 'Navigate to Liderlik and re-tap its tab.', 'The committed route remains /leaderboard with one Leaderboard root.', { selector: '[data-testid="bottom-nav-leaderboard"]' }),
      step('nav.exact_tabs', 'Recheck tab set', 'Read all visible BottomNav labels.', 'No fourth tab or Online-owned tab exists.', { selector: '[data-testid="bottom-nav"]' }),
    ],
    successCriteria: ['Route, content, and active tab agree', 'Profile subroute re-tap resets to Profile root', 'Exactly three tabs remain'],
    failureCategories: ['ROUTE_TAB_DESYNC', 'STALE_SUBROUTE', 'BOTTOM_NAV_CONTRACT_DRIFT'],
    manualFallback: 'Repeat on a physical WebView if browser history behavior differs from desktop Chromium.',
  }),
  scenario({
    scenarioId: 'runtime_e2e.profile_navigation_privacy',
    title: 'Profile navigation and privacy',
    description: 'Checks Profile root, current edit route/back behavior, allowed fields, and the public/private identity boundary.',
    riskArea: 'profile_privacy',
    maxExpectedDuration: 45000,
    requiredCapabilities: ['browser', 'appDocument', 'appConfig', 'base44Backend', 'guestBootstrap', 'completedActor'],
    executionScope: RUNTIME_E2E_EXECUTION_SCOPE.BACKEND_DEPENDENT,
    backendServices: ['base_app', 'actor_bootstrap', 'profile'],
    testUserStrategy: 'Uses an isolated completed guest where possible. No profile value is changed or saved.',
    steps: [
      step('profile.open', 'Open Profile root', 'Tap the Profil BottomNav item.', 'The Profile screen root is visible.', { selector: '[data-testid="profile-screen"]' }),
      step('profile.identity', 'Verify safe identity area', 'Locate the username/avatar identity card or safe fallback.', 'A user-facing identity area is visible without email.'),
      step('profile.edit_open', 'Open Profile Edit', 'Tap Profil Bilgileri.', 'The Profile Edit screen is visible.', { selector: '[data-testid="profile-edit-entry"]' }),
      step('profile.fields', 'Verify editable fields', 'Inspect current Profile Edit labels when the actor profile is available.', 'Takma Ad, Cinsiyet, Yaş grubu, and current category support are visible; otherwise the optional check is NOT_AUTOMATABLE.', { required: false, selector: '[data-testid="profile-edit-screen"]' }),
      step('profile.privacy', 'Scan Profile privacy', 'Inspect rendered Profile/Edit text for private identity fields and email.', 'No owner key, guest token/id, provider/auth id, internal player key, or email is rendered.'),
      step('profile.back', 'Use Profile back control', 'Tap the Profile Edit back button.', 'The Profile root returns.', { selector: '[data-testid="profile-edit-back"]' }),
      step('profile.home', 'Return Home', 'Tap Ana Sayfa.', 'Home appears with Ana Sayfa active.', { selector: '[data-testid="bottom-nav-home"]' }),
    ],
    successCriteria: ['Profile/Edit navigation works', 'Back returns to Profile root', 'No private fields leak'],
    failureCategories: ['PROFILE_ROUTE_FAILURE', 'PROFILE_BACK_FAILURE', 'PRIVATE_DATA_EXPOSURE'],
    manualFallback: 'Verify linked-provider edit/save behavior with a dedicated non-production test account.',
  }),
  scenario({
    scenarioId: 'runtime_e2e.leaderboard_smoke_privacy',
    title: 'Leaderboard smoke and privacy',
    description: 'Verifies the Leaderboard renders a list, own row, or safe state without raw errors or private identity fields.',
    riskArea: 'leaderboard_privacy',
    maxExpectedDuration: 45000,
    requiredCapabilities: ['browser', 'appDocument', 'appConfig', 'base44Backend', 'guestBootstrap', 'completedActor'],
    executionScope: RUNTIME_E2E_EXECUTION_SCOPE.BACKEND_DEPENDENT,
    backendServices: ['base_app', 'leaderboard'],
    testUserStrategy: 'Read-only with a completed guest/test actor; it does not alter score or friendship.',
    steps: [
      step('leaderboard.open', 'Open Leaderboard', 'Tap Liderlik.', 'The Leaderboard screen root and heading are visible.', { selector: '[data-testid="leaderboard-screen"]' }),
      step('leaderboard.state', 'Verify safe data state', 'Wait for a ranking list, current-player row, empty state, or retry state.', 'A bounded user-facing state is visible rather than a blank screen.'),
      step('leaderboard.score', 'Verify score presentation', 'Inspect visible score rows when data exists.', 'Scores use the Puan/Kronox Puan presentation without a raw object.'),
      step('leaderboard.privacy', 'Scan Leaderboard privacy', 'Inspect rendered text for raw errors, stack traces, email, or internal keys.', 'No private identity or raw backend detail is shown.'),
      step('leaderboard.home', 'Return Home', 'Tap Ana Sayfa.', 'Home is visible and active.', { selector: '[data-testid="bottom-nav-home"]' }),
    ],
    successCriteria: ['Leaderboard renders a safe state', 'No private data or raw backend error is visible'],
    failureCategories: ['LEADERBOARD_BLANK', 'LEADERBOARD_RAW_ERROR', 'PRIVATE_DATA_EXPOSURE'],
    manualFallback: 'Exercise very large ranking pages against a staging dataset when available.',
  }),
  scenario({
    scenarioId: 'runtime_e2e.daily_screen_smoke_no_claim',
    title: 'Daily screen smoke without claim',
    description: 'Opens the Daily Calendar/tasks route, observes the current state, and leaves without claiming or completing anything.',
    riskArea: 'daily_non_mutating',
    maxExpectedDuration: 45000,
    requiredCapabilities: ['browser', 'appDocument', 'appConfig', 'base44Backend', 'guestBootstrap', 'completedActor'],
    executionScope: RUNTIME_E2E_EXECUTION_SCOPE.BACKEND_DEPENDENT,
    backendServices: ['base_app', 'daily_status'],
    testUserStrategy: 'Read-only completed guest/test actor. The scenario never taps a claim or task-completion action.',
    steps: [
      step('daily.open', 'Open Daily', 'Tap the Home GÜNLÜK shortcut.', 'The /daily screen root appears.', { selector: '[data-testid="daily-screen-entry"]' }),
      step('daily.root', 'Verify Daily root', 'Locate calendar and page title.', 'The Daily screen is visible.', { selector: '[data-testid="daily-screen"]' }),
      step('daily.tasks', 'Verify task state', 'Locate today tasks or a safe loading/empty/retry state.', 'A bounded current Daily state is rendered.'),
      step('daily.streak', 'Verify streak/progress state', 'Inspect the current streak/progress area when available.', 'The area is visible or honestly absent for the current response.'),
      step('daily.no_claim', 'Keep the run non-mutating', 'Do not click claim, task, or reward controls.', 'No claim or task mutation is requested.'),
      step('daily.back', 'Return Home', 'Use the Daily back button.', 'Home is visible with no overlay.', { selector: '[data-testid="daily-back-home"]' }),
    ],
    successCriteria: ['Daily opens', 'No reward claim occurs', 'No Puan/Leaderboard mutation is triggered'],
    failureCategories: ['DAILY_ROUTE_FAILURE', 'DAILY_LOADING_DEADLOCK', 'UNEXPECTED_MUTATION'],
    manualFallback: 'Use a resettable staging actor for reward-claim coverage; this V1 smoke remains read-only.',
  }),
  scenario({
    scenarioId: 'runtime_e2e.daily_wheel_open_close_optional_spin',
    title: 'Daily Wheel open/close and optional spin',
    description: 'Proves modal/overlay cleanup. A free spin runs only behind the explicit KRONOX_E2E_ALLOW_WHEEL_SPIN gate.',
    riskArea: 'daily_wheel_overlay_economy',
    maxExpectedDuration: 60000,
    requiredCapabilities: ['browser', 'appDocument', 'appConfig', 'base44Backend', 'guestBootstrap', 'completedActor'],
    optionalCapabilities: ['mutationSafeWheelActor'],
    executionScope: RUNTIME_E2E_EXECUTION_SCOPE.BACKEND_DEPENDENT,
    backendServices: ['base_app', 'daily_wheel'],
    testUserStrategy: 'Open/close is non-mutating. Spin requires an isolated resettable actor plus KRONOX_E2E_ALLOW_WHEEL_SPIN=true.',
    steps: [
      step('wheel.balance_before', 'Capture visible Diamonds', 'Read the Home Diamond chip when available.', 'A numeric pre-action balance or an explicit unavailable value is recorded.'),
      step('wheel.open', 'Open Daily Wheel', 'Tap the Home Çark shortcut.', 'The full Daily Wheel modal appears.', { selector: '[data-testid="daily-wheel-entry"]' }),
      step('wheel.modal', 'Verify modal and close control', 'Locate the dialog and close control.', 'A centered modal and reachable close action are visible.', { selector: '[data-testid="daily-wheel-modal"]' }),
      step('wheel.close', 'Close Daily Wheel', 'Tap close/SONRA without spinning.', 'The dialog and backdrop unmount.', { selector: '[data-testid="daily-wheel-close"]' }),
      step('wheel.home_interactive', 'Verify overlay cleanup', 'Use a safe Home control after close.', 'Home remains interactive and no hidden overlay intercepts input.'),
      step('wheel.reopen', 'Reopen Daily Wheel', 'Tap Çark again.', 'The current available or claimed read-only result appears.', { selector: '[data-testid="daily-wheel-entry"]' }),
      step('wheel.optional_spin', 'Optionally run a safe spin', 'Spin only when the explicit mutation gate and a free isolated state are available.', 'The backend-selected result appears; otherwise this optional step is NOT_AUTOMATABLE.', { required: false, selector: '[data-testid="daily-wheel-spin"]' }),
      step('wheel.no_puan', 'Protect score boundary', 'Compare visible Puan only when an optional spin ran.', 'Daily Wheel never grants Kronox Puan.', { required: false }),
    ],
    successCriteria: ['Open/close works', 'No overlay leak', 'Optional spin runs only in safe state'],
    failureCategories: ['WHEEL_MODAL_FAILURE', 'OVERLAY_LEAK', 'WHEEL_RESULT_STUCK', 'UNEXPECTED_SCORE_MUTATION'],
    manualFallback: 'Reset a dedicated staging actor through the approved admin tool, set KRONOX_E2E_ALLOW_WHEEL_SPIN=true, and rerun.',
  }),
  scenario({
    scenarioId: 'runtime_e2e.store_smoke_disabled_real_money',
    title: 'Store smoke and disabled real-money safety',
    description: 'Checks the current Home top-bar Store path, disabled Yakında products, and the absence of a fake IAP flow.',
    riskArea: 'store_payment_safety',
    maxExpectedDuration: 50000,
    requiredCapabilities: ['browser', 'appDocument', 'uiOnly', 'completedActor'],
    optionalCapabilities: ['mutationSafeStoreActor'],
    executionScope: RUNTIME_E2E_EXECUTION_SCOPE.UI_ONLY,
    testUserStrategy: 'Real-money controls are inspected only. Diamond purchase requires KRONOX_E2E_ALLOW_DIAMOND_PURCHASE=true and an isolated funded actor.',
    steps: [
      step('store.open', 'Open Store from Home', 'Use the Home Mağaza top-bar button.', 'The /market Store route opens.', { selector: '[data-testid="store-entry"]' }),
      step('store.root', 'Verify Store root', 'Locate the Mağaza screen.', 'Store content is visible.', { selector: '[data-testid="store-screen"]' }),
      step('store.catalog', 'Verify catalog lanes', 'Inspect Diamond and inventory package sections.', 'Current catalog sections render or show a safe state.'),
      step('store.future_disabled', 'Verify future real-money products', 'Inspect TL Diamond packs, KronoClub, and Reklamları Kaldır.', 'Their actions are disabled and labeled Yakında.', { selector: '[data-testid="store-future-product"]' }),
      step('store.no_payment', 'Verify no payment flow', 'Attempt only a DOM click on a disabled future action.', 'No payment/native modal or fake purchase success opens.'),
      step('store.optional_diamond_purchase', 'Optionally buy a Diamond-priced item', 'Run only with an isolated funded actor and explicit mutation gate.', 'Balance/inventory refreshes correctly; otherwise the optional step is NOT_AUTOMATABLE.', { required: false }),
      step('store.home', 'Return Home', 'Use Store back navigation.', 'Home appears without stale modal state.'),
    ],
    successCriteria: ['Store renders', 'Real-money paths remain disabled', 'No fake IAP occurs'],
    failureCategories: ['STORE_ROUTE_FAILURE', 'REAL_MONEY_ENABLED', 'FAKE_PAYMENT_FLOW', 'UNEXPECTED_SCORE_MUTATION'],
    manualFallback: 'Use an isolated funded staging actor for Diamond-spend inventory assertions.',
  }),
  scenario({
    scenarioId: 'runtime_e2e.solo_gameplay_smoke',
    title: 'Solo gameplay smoke',
    description: 'Opens the current Solo level from the Home-owned level map, verifies its real gameplay surface, and exits through the in-game back control.',
    riskArea: 'solo_start_exit',
    maxExpectedDuration: 70000,
    requiredCapabilities: ['browser', 'appDocument', 'appConfig', 'base44Backend', 'guestBootstrap', 'completedActor', 'questionBootstrap', 'soloQuestionService'],
    executionScope: RUNTIME_E2E_EXECUTION_SCOPE.BACKEND_DEPENDENT,
    backendServices: ['base_app', 'actor_bootstrap', 'question_service'],
    testUserStrategy: 'Uses the actor current level and performs no evaluated placement. Tutorial acknowledgment is allowed; no reward is claimed.',
    steps: [
      step('solo.start', 'Start current Solo level', 'Tap Home OYNA, wait for the actual /solo level map, then tap the current playable level.', 'The selected level opens /game and Solo question preparation starts.', { selector: '[data-testid="home-solo-entry"], [data-testid="solo-current-level-entry"]' }),
      step('solo.root', 'Verify Solo game root', 'Wait for the gameplay root after bounded question preparation.', 'The Solo gameplay screen is visible.', { selector: '[data-testid="solo-game-screen"]' }),
      step('solo.question', 'Verify question/card area', 'Locate the current question card and timeline interaction area.', 'A playable question and timeline target are visible.', { selector: '[data-testid="solo-question-area"]' }),
      step('solo.progress', 'Verify progress/timer', 'Inspect remaining moves and progress/timer controls.', 'Current progress and timing/move state are visible.'),
      step('solo.tutorial', 'Handle optional tutorial popup', 'Acknowledge the current tutorial popup only if it is present.', 'The popup closes and gameplay resumes.', { required: false }),
      step('solo.interaction_target', 'Verify interaction target', 'Locate a draggable card or valid drop/timeline target.', 'At least one gameplay interaction target is visible.'),
      step('solo.exit', 'Exit safely', 'Tap the in-game Geri dön control without evaluating a move.', 'Direct Home launches return Home; map launches return the Solo map.', { selector: '[data-testid="solo-back-home"]' }),
      step('solo.cleanup', 'Verify route/overlay cleanup', 'Inspect the expected parent after exit.', 'The expected parent is active and no gameplay overlay remains.'),
    ],
    successCriteria: ['Solo opens', 'No loading deadlock', 'Exit cleanup returns to the launch-specific parent'],
    failureCategories: [
      'SOLO_LOAD_FAILURE',
      'QUESTION_SERVICE_FAILURE',
      'SOLO_UI_BLOCKED',
      'SOLO_EXIT_CONTROL_MISSING',
      'SOLO_EXIT_CONTROL_HIDDEN',
      'SOLO_EXIT_BLOCKED_BY_OVERLAY',
      'SOLO_EXIT_BLOCKED_BY_TUTORIAL',
      'SOLO_EXIT_CLICK_TIMEOUT',
      'SOLO_EXIT_ROUTE_STALL',
    ],
    manualFallback: 'Rerun against a deployed question service or approved local fixture if question bootstrap is unavailable.',
  }),
  scenario({
    scenarioId: 'runtime_e2e.online_random_waiting_cancel_smoke',
    title: 'Online Kapış no-lobby direct-start smoke',
    description: 'Opens /online, proves the bounded search/cancel lifecycle, then requires same-screen match-found and a backend-authoritative direct /game transition or a precise two-actor gap.',
    riskArea: 'online_direct_start',
    maxExpectedDuration: 90000,
    requiredCapabilities: ['browser', 'appDocument', 'appConfig', 'base44Backend', 'completedActor', 'onlineMatchmaking', 'safeMatchmakingQueue'],
    executionScope: RUNTIME_E2E_EXECUTION_SCOPE.BACKEND_DEPENDENT,
    backendServices: ['base_app', 'actor_bootstrap', 'online_matchmaking'],
    testUserStrategy: 'Use a completed linked or token-proven guest actor with KRONOX_E2E_ALLOW_MATCHMAKING=true. A second isolated actor is required to prove match-found/direct-start.',
    steps: [
      step('online.open', 'Open Online', 'Tap the actual Home ONLINE KAPIŞ CTA.', 'The canonical /online root opens without /lobby.', { selector: '[data-testid="home-online-entry"]' }),
      step('online.root', 'Verify Online root', 'Locate the Online challenge screen.', 'The Online screen is visible.', { selector: '[data-testid="online-screen"]' }),
      step('online.options', 'Verify current mode options', 'Locate Arkadaşını Davet Et, Online Kapış, and Duello.', 'All current options are visible.'),
      step('online.no_category', 'Verify category isolation', 'Inspect the Online setup surface.', 'No Solo category selector is rendered.'),
      step('online.random_start', 'Start Online Kapış search', 'With the explicit safe queue gate, tap Online Kapış.', 'The search screen appears after a successful backend response.', { selector: '[data-testid="online-kapis-entry"]' }),
      step('online.waiting', 'Verify search state', 'Locate Rakip aranıyor and the cancel action.', 'A bounded 30-second search state is visible.', { selector: '[data-testid="online-kapis-search-screen"]' }),
      step('online.cancel', 'Cancel search safely', 'Tap Vazgeç.', 'The /online root returns and the stale search surface closes.', { selector: '[data-testid="online-kapis-search-cancel"]' }),
      step('online.restart', 'Restart matchmaking', 'Start Online Kapış again for direct-start proof.', 'A second successful backend queue response is observed.'),
      step('online.matched', 'Verify same-screen match found', 'Wait for a second actor to pair.', 'Rakip bulundu appears on the same search surface and /lobby is never observed.', { selector: '[data-testid="online-match-found-screen"]' }),
      step('online.direct_game', 'Verify direct game start', 'Observe the bounded matched transition.', 'The app enters /game and the Online gameplay root without an intermediate lobby.', { selector: '[data-testid="online-game-screen"]' }),
      step('online.cleanup', 'Verify Online privacy and route evidence', 'Inspect route history, match evidence, and public text.', 'No lobby surface, stale search UI, private identifier, or raw backend detail remains.'),
    ],
    successCriteria: ['Search/cancel completes', 'Rakip bulundu appears on the same screen', 'Backend-authoritative /game starts directly', 'No /lobby route or screen appears'],
    failureCategories: ['LOBBY_STILL_PRESENT', 'MATCH_FOUND_DIRECT_GAME_PENDING', 'TWO_ACTOR_REQUIRED', 'PRIVATE_DATA_EXPOSURE'],
    manualFallback: 'Run two isolated actors against the same safe environment to prove matched and direct-game phases.',
  }),
  scenario({
    scenarioId: 'runtime_e2e.duello_two_context_runtime_sync',
    title: 'Duello two-actor pairing and direct-start sync',
    description: 'Uses two isolated actors to prove same-screen match-found, no-lobby direct /duel start, and a shared public-safe session/card fingerprint.',
    riskArea: 'duello_pairing_direct_start',
    maxExpectedDuration: 120000,
    requiredCapabilities: ['browser', 'appDocument', 'appConfig', 'base44Backend', 'safeMatchmakingQueue', 'twoBrowserContexts', 'twoIsolatedActors', 'deterministicTwoActorPairing'],
    optionalCapabilities: ['deterministicClaimFixture'],
    executionScope: RUNTIME_E2E_EXECUTION_SCOPE.BACKEND_DEPENDENT,
    backendServices: ['base_app', 'actor_bootstrap', 'online_matchmaking'],
    testUserStrategy: 'Uses KRONOX_E2E_STORAGE_STATE_A/B only in an approved environment. Missing A/B fixtures returns MANUAL_EXTERNAL; claim-race fairness remains separate and optional.',
    steps: [
      step('duello.contexts', 'Open two isolated contexts', 'Create contexts A and B with separate test actors.', 'Both actors independently reach Home.'),
      step('duello.entries', 'Open Duello entry in both', 'Navigate both actors through Online and locate Duello.', 'The exact Duello label is visible in both contexts.', { selector: '[data-testid="duello-entry"]' }),
      step('duello.match', 'Match the same two-player session', 'Join the mode-scoped queue in both contexts.', 'Both contexts show Rakip bulundu on the same search screen and enter /duel directly without /lobby.'),
      step('duello.active_card', 'Verify shared active card', 'Capture the public-safe active sequence/card fingerprint in A and B.', 'Both fingerprints and revisions match.', { selector: '[data-testid="duello-active-card"]' }),
      step('duello.privacy', 'Verify public snapshot privacy', 'Inspect both rendered surfaces and captured report output.', 'No answer year, raw Question id, private actor key, auth/session token, or raw backend error appears.'),
      step('duello.cleanup', 'Close both isolated contexts safely', 'Allow the runner to close A and B after proof.', 'No search poller or browser context remains active.'),
      step('duello.extended_result', 'Optional first-to-10 result proof', 'Complete the deterministic match only when a dedicated fixture exists.', 'Winner +15 and loser -6 commit once.', { required: false }),
    ],
    successCriteria: ['Both actors see same-screen Rakip bulundu', 'Both enter /duel without /lobby', 'Session and active-card fingerprints match', 'No private/full-deck data leaks'],
    failureCategories: ['DUELLO_SETUP_GAP', 'DUELLO_PAIRING_FAILURE', 'LOBBY_STILL_PRESENT', 'DUELLO_SNAPSHOT_DIVERGENCE', 'PRIVATE_DATA_EXPOSURE'],
    manualFallback: 'Provide two distinct KRONOX_E2E_STORAGE_STATE_A/B files or run the documented physical two-device proof.',
  }),
]);

export const RUNTIME_E2E_SUITE = Object.freeze({
  id: RUNTIME_E2E_SUITE_ID,
  name: 'Runtime E2E Automation Health Suite',
  description: 'Ayrı otomasyon raporu',
  fullRunExcluded: true,
  externalAutomation: true,
  scenarioCount: RUNTIME_E2E_SCENARIOS.length,
  critical: false,
  color: '#38bdf8',
});

export function getRuntimeE2EScenario(scenarioId) {
  return RUNTIME_E2E_SCENARIOS.find((item) => item.scenarioId === scenarioId) || null;
}
